version: '3'
services:
  couchdb_container:
    image: couchdb:latest
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    volumes:
      - ./dbdata:/opt/couchdb/data
    
  backend_container:
    build: ./backend_container
    ports:
      - "3000:3000"
    depends_on:
      - couchdb_container
  
  frontend_container:
    build: ./frontend_container
    ports:
      - "3001:8080"
    depends_on:
      - backend_container

volumes:
  dbdata:
